site_name: Django GDPR Cookie Consent
site_url: https://archatas.github.io/django-gdpr-cookie-consent-docs/
site_description: Django GDPR Cookie Consent documentation
site_author: Aidas Bendoraitis a.k.a. archatas / DjangoTricks
docs_dir: src
site_dir: docs
repo_url: https://websightful.gumroad.com/l/django-gdpr-cookie-consent
repo_name: Buy Now!
extra_css:
  - css/style.css

nav:
    - Home: 'index.md'
    - Getting Started: 'getting-started.md'
    - Customization: 'customization.md'
    - 'More':
        - Settings Example: 'cookie-consent-settings.md'
        - Changelog: 'changelog.md'
        - License: 'license.md'